#!/bin/bash
yum groupinstall -y "Web Server" "MySQL Database" "PHP Support"
yum install -y php-mysql

cd /home/ec2-user/
curl -sS https://getcomposer.org/installer | php
mv composer.phar /usr/local/bin/composer
ln -sf /usr/local/bin/composer /usr/bin/composer