#!/bin/bash

yum install -y httpd
yum install -y php70
yum install -y php70-gd
yum install -y php70-imap
yum install -y php70-mbstring
yum install -y php70-mysqli
yum install -y php70-opcache
yum install -y php70-pecl-apcu

cd /home/ec2-user/
curl -sS https://getcomposer.org/installer | php
mv composer.phar /usr/local/bin/composer
ln -sf /usr/local/bin/composer /usr/bin/composer
