#!/bin/bash

touch /var/www/html/.env

db_host=$(aws ssm get-parameters --region eu-central-1 --names HACKERNEWS_DB_HOST --with-decryption --query Parameters[0].Value)
db_user=$(aws ssm get-parameters --region eu-central-1 --names HACKERNEWS_DB_USER --with-decryption --query Parameters[0].Value)
db_password=$(aws ssm get-parameters --region eu-central-1 --names HACKERNEWS_DB_PASS --with-decryption --query Parameters[0].Value)
db_schema=$(aws ssm get-parameters --region eu-central-1 --names HACKERNEWS_DB_SCHEMA --with-decryption --query Parameters[0].Value)
jwt_secret=$(aws ssm get-parameters --region eu-central-1 --names HACKERNEWS_JWT_SECRET --with-decryption --query Parameters[0].Value)
aws_region=$(aws ssm get-parameters --region eu-central-1 --names HACKERNEWS_AWS_REGION --with-decryption --query Parameters[0].Value)
aws_version=$(aws ssm get-parameters --region eu-central-1 --names HACKERNEWS_AWS_VERSION --with-decryption --query Parameters[0].Value)
aws_cw_group=$(aws ssm get-parameters --region eu-central-1 --names HACKERNEWS_AWS_CW_GROUP --with-decryption --query Parameters[0].Value)
aws_cw_stream=$(aws ssm get-parameters --region eu-central-1 --names HACKERNEWS_AWS_CW_STREAM --with-decryption --query Parameters[0].Value)
aws_cw_retention=$(aws ssm get-parameters --region eu-central-1 --names HACKERNEWS_AWS_CW_RETENTION --with-decryption --query Parameters[0].Value)
aws_cw_log_name=$(aws ssm get-parameters --region eu-central-1 --names HACKERNEWS_AWS_CW_LOG_NAME --with-decryption --query Parameters[0].Value)
aws_cw_app_name=$(aws ssm get-parameters --region eu-central-1 --names HACKERNEWS_AWS_CW_APP_NAME --with-decryption --query Parameters[0].Value)
aws_cw_log_identifier=$(aws ssm get-parameters --region eu-central-1 --names HACKERNEWS_AWS_CW_LOG_IDENTIFIER --with-decryption --query Parameters[0].Value)
aws_local_log_identifier=$(aws ssm get-parameters --region eu-central-1 --names HACKERNEWS_LOCAL_LOG_IDENTIFIER --with-decryption --query Parameters[0].Value)
aws_local_log_name=$(aws ssm get-parameters --region eu-central-1 --names HACKERNEWS_LOCAL_LOG_NAME --with-decryption --query Parameters[0].Value)
aws_key=$(aws ssm get-parameters --region eu-central-1 --names HACKERNEWS_AWS_KEY --with-decryption --query Parameters[0].Value)
aws_secret=$(aws ssm get-parameters --region eu-central-1 --names HACKERNEWS_AWS_SECRET --with-decryption --query Parameters[0].Value)
instance_id=$(ec2-metadata --instance-id | cut -d " " -f 2)

echo "DB_HOST=$db_host" >> /var/www/html/.env
echo "DB_USER=$db_user" >> /var/www/html/.env
echo "DB_PASS=$db_password" >> /var/www/html/.env
echo "DB_SCHEMA=$db_schema" >> /var/www/html/.env
echo "JWT_SECRET=$jwt_secret" >> /var/www/html/.env
echo "AWS_REGION=$aws_region" >> /var/www/html/.env
echo "AWS_VERSION=$aws_version" >> /var/www/html/.env
echo "AWS_CW_GROUP=$aws_cw_group" >> /var/www/html/.env
echo "AWS_CW_STREAM=$aws_cw_stream" >> /var/www/html/.env
echo "AWS_CW_RETENTION=$aws_cw_retention" >> /var/www/html/.env
echo "AWS_CW_LOG_NAME=$aws_cw_log_name" >> /var/www/html/.env
echo "AWS_CW_APP_NAME=$aws_cw_app_name" >> /var/www/html/.env
echo "AWS_CW_LOG_IDENTIFIER=$aws_cw_log_identifier" >> /var/www/html/.env
echo "LOCAL_LOG_IDENTIFIER=$aws_local_log_identifier" >> /var/www/html/.env
echo "LOCAL_LOG_NAME=$aws_local_log_name" >> /var/www/html/.env
echo "AWS_KEY=$aws_key" >> /var/www/html/.env
echo "AWS_SECRET=$aws_secret" >> /var/www/html/.env
echo "AWS_INSTANCE_ID=$instance_id" >> /var/www/html/.env
